#!/usr/bin/env bash

yabai -m config \
    layout bsp \
    split_ratio 0.5

yabai -m rule --add app="^System Prefences$" manage=off
yabai -m rule --add title="^kitty_float$" manage=off
#yabai -m rule --add title="Teams$" manage=off

yabai -m config --space 10 layout float
